

#!/bin/bash

export ALIEN_JDL_LPMANCHORPASSNAME=${ALIEN_JDL_LPMANCHORPASSNAME:-"apass7"}
export ALIEN_JDL_MCANCHOR=${ALIEN_JDL_MCANCHOR:-"apass7"}
export ALIEN_JDL_LPMPASSNAME=${ALIEN_JDL_LPMPASSNAME:-"apass7"}
export ALIEN_JDL_LPMRUNNUMBER=${ALIEN_JDL_LPMRUNNUMBER:-"526641"}
export ALIEN_JDL_LPMPRODUCTIONTYPE=${ALIEN_JDL_LPMPRODUCTIONTYPE:-"MC"}
export ALIEN_JDL_LPMINTERACTIONTYPE=${ALIEN_JDL_LPMINTERACTIONTYPE:-"pp"}
export ALIEN_JDL_LPMANCHORRUN=${ALIEN_JDL_LPMANCHORRUN:-"526641"}
export ALIEN_JDL_LPMANCHORPRODUCTION=${ALIEN_JDL_LPMANCHORPRODUCTION:-"LHC22o"}
export ALIEN_JDL_LPMANCHORYEAR=${ALIEN_JDL_LPMANCHORYEAR:-"2022"}

# added export
export NTIMEFRAMES=8
export NSIGEVENTS=500
export SPLITID=1
export CYCLE=0
export PRODSPLIT=8

export ALIEN_JDL_ANCHOR_SIM_OPTIONS="-gen external -ini $O2DPG_ROOT/MC/config/PWGDQ/ini/Generator_InjectedPromptCharmoniaFwdy_TriggerGap.ini"

#/alice/cern.ch/user/l/lmichele/selfjobs/TestPromptCharmoniaAnchorFwd22pass7/anchorMC.sh
#${O2DPG_ROOT}/MC/run/ANCHOR/anchorMC.sh

chmod +x ./anchorMC.sh
./anchorMC.sh

